actions:
- button:
  - 0
  - 0
  name: multi
  parameters:
    render:
      name: homeassistant_light
      parameters:
        domain: light
        entity: light.hue_color_lamp_1_3
        off_icon: icons/floor_light_top_off.png
        on_icon: icons/floor_light_top_on.png
    run:
    - conditions:
      - max: 300ms
        min: 10ms
        pressed: true
      - min: 100ms
        pressed: false
      name: homeassistant_light
      parameters:
        domain: light
        entity: light.hue_color_lamp_1_3
        service_name: turn_on
      pressed: true
    - conditions:
      - max: 1000ms
        min: 500ms
        pressed: true
      name: homeassistant_light
      parameters:
        domain: light
        entity: light.hue_color_lamp_1_3
        service_name: turn_off
      pressed: true
- button:
  - 0
  - 1
  name: multi
  parameters:
    render:
      name: homeassistant_light
      parameters:
        domain: light
        entity: light.hue_color_candle_1_2
        off_icon: icons/floor_light_bottom_off.png
        on_icon: icons/floor_light_bottom_on.png
    run:
    - conditions:
      - max: 300ms
        min: 10ms
        pressed: true
      - min: 100ms
        pressed: false
      name: homeassistant_light
      parameters:
        domain: light
        entity: light.hue_color_candle_1_2
        service_name: turn_on
      pressed: true
    - conditions:
      - max: 1000ms
        min: 500ms
        pressed: true
      name: homeassistant_light
      parameters:
        domain: light
        entity: light.hue_color_candle_1_2
        service_name: turn_off
      pressed: true
- button:
  - 1
  - 0
  name: multi
  parameters:
    render:
      name: homeassistant_light
      parameters:
        domain: light
        entity: light.hue_lightguide_bulb_1
        off_icon: icons/ceiling_light_off.png
        on_icon: icons/ceiling_light_on.png
    run:
    - conditions:
      - max: 300ms
        min: 10ms
        pressed: true
      - min: 100ms
        pressed: false
      name: homeassistant_light
      parameters:
        domain: light
        entity: light.hue_lightguide_bulb_1
        service_name: turn_on
      pressed: true
    - conditions:
      - max: 1000ms
        min: 500ms
        pressed: true
      name: homeassistant_light
      parameters:
        domain: light
        entity: light.hue_lightguide_bulb_1
        service_name: turn_off
      pressed: true
