actions:
- button: [0,0]
  name: homeassistant_light
  parameters:
    domain: light
    entity: light.tv_left_light
    service_name: toggle

    on_icon: icons/light_on.png
    off_icon: icons/light_off.png

- button: [0,1]
  name: homeassistant_entity
  parameters:
    domain: fan
    entity: fan.corner_ceiling_fan
    service_name: set_percentage

    icon: icons/fan.png
    service_data:
      percentage: 30

    conditions:
    - icon: icons/fan_3.png
      service_data:
        percentage: 0
      condition:
        src: percentage
        comparison: gt
        value: 70
    - icon: icons/fan_2.png
      service_data:
        percentage: 100
      condition:
        src: percentage
        comparison: gt
        value: 40
    - icon: icons/fan_1.png
      service_data:
        percentage: 50
      condition:
        src: percentage
        comparison: gt
        value: 0
    - icon: icons/fan_0.png
      condition:
        src: percentage
        comparison: gt
        value: 0
