actions:
- button: [0,0]
  name: homeassistant_light
  parameters:
    domain: light
    entity: light.tv_left_light
    service_name: toggle

    icon: light.png
    icons:
    - file: exit.png
      condition:
        comparison: ==
        value: on
    - file: idle.png
      condition:
        comparison: ==
        value: off
