actions:
- button: [0,0]
  name: brightness
  parameters:
    icon: running.png
    brightness: 0
- button: [1,0]
  name: brightness
  parameters:
    icon: running.png
    brightness: 50
- button: [2,0]
  name: brightness
  parameters:
    icon: running.png
    brightness: 100
  
- button: [1,1]
  name: homeassistant_entity
  parameters:
    domain: light
    entity: light.office_desk_strip
    service_name: toggle

    default_icon: running.png
    icons:
    - file: exit.png
      condition:
        comparison: ==
        value: on
    - file: idle.png
      condition:
        comparison: ==
        value: off
