actions:
- button: [1,1]
  name: command
  parameters:
    command: ping 
    args: ["-c2", "127.0.0.1"]
    icon: idle.png
    running_icon: running.png
    exit_default_icon: exit.png
    exit_to_idle_time: 5s
